### ISSUE TITLE
Data decryption failed

### ISSUE THREAD

**Issue by baurmatt** [rnurgaliyev/co2meter_exporter#2]
When running your exporter I get an error message about failed decryption:

```bash
s0me0ne@s0me0ne-T14s:/tmp$ sudo ~/go/bin/co2meter_exporter -d /dev/hidraw0
2021/02/12 14:36:34 Listening on http://0.0.0.0:9200/metrics
2021/02/12 14:36:35 Data decryption failed:  [0 234 204 41 204 0 155 24]
```

The python library for co2 meter seems to have run in the same problem and solve it by just skipping decryption of retrieved values -> https://github.com/vfilimonov/co2meter/issues/16 / https://github.com/vfilimonov/co2meter/commit/5d4187dbd666163911601e0076336e42a4045afc

I will provide a PR.

**Comment by rnurgaliyev** [comment]
Thank you for reporting this issue!
